files:
  - source: /src/main/res/values/strings.xml
    translation: /src/main/res/values-%two_letters_code%/strings.xml
    translate_content: '0'
    translate_attributes: '0'
    content_segmentation: '0'
